### ISSUE TITLE
Docs: Add contribution checklist to PR template

### ISSUE THREAD

**Issue by strbit** [jarsft/.github#5]
### Type of correction

Documentation

### Additional information

Contributors should confirm their pull-requests follow the required standards, such as:

* ... that all code (if available within the pull-request or the repository) runs without any errors or warnings.
* ... that the PR follows the [Contribution Guidelines](https://github.com/jarsft/.github/blob/production/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/jarsft/.github/blob/production/CODE_OF_CONDUCT.md).
* ... that all unit tests (if available) pass, and that new tests are added.
* ... no other pull-requests or contributions were broken as a result of their pull-request.

### Submission checklist

- [X] Follow the [Code of Conduct](https://github.com/jarsft/.github/blob/production/CODE_OF_CONDUCT.md)
- [X] Read the [Contribution Guide](https://github.com/jarsft/.github/blob/production/CONTRIBUTING.md)
- [X] Check that no issue that reports the same correction exists.
- [X] Check that no other elements other than the documentation were modified.
